// Configuration for the frontend application
// Auto-generated by sync-configs.sh

export const config = {
  aws: {
    region: 'us-west-2'
  },
  connect: {
    instanceId: '602d4c63-50be-4b56-ac69-6068140d5a61',
    contactFlowId: 'c539c831-a1fa-4b03-8438-568143a865dd'
  },
  api: {
    endpoint: 'https://lc55ximwma.execute-api.us-west-2.amazonaws.com/prod/'
  },
  websocket: {
    url: 'wss://2jn06ucuwi.execute-api.us-west-2.amazonaws.com/prod'
  }
};
