#!/bin/bash

# Script to sync configurations across frontend and agent-app from central config.json

set -e

echo "🔧 Syncing configurations from central config.json..."

# Read central config
REGION=$(jq -r '.aws.region' config.json)
INSTANCE_ID=$(jq -r '.connect.instanceId' config.json)
CONTACT_FLOW_ID=$(jq -r '.connect.contactFlowId' config.json)
CCP_URL=$(jq -r '.connect.ccpUrl' config.json)

echo "✅ Loaded central config:"
echo "   Region: $REGION"
echo "   Instance ID: $INSTANCE_ID"
echo "   CCP URL: $CCP_URL"
echo ""

# Get the API URL from CDK outputs
echo "🔍 Fetching deployed API URLs from CloudFormation..."
cd infra
API_URL=$(aws cloudformation describe-stacks \
  --region $REGION \
  --stack-name ConnectMultimodalStack \
  --query 'Stacks[0].Outputs[?OutputKey==`ApiURL`].OutputValue' \
  --output text)

WEBSOCKET_URL=$(aws cloudformation describe-stacks \
  --region $REGION \
  --stack-name ConnectMultimodalStack \
  --query 'Stacks[0].Outputs[?OutputKey==`WebSocketURL`].OutputValue' \
  --output text)

if [ -z "$API_URL" ]; then
  echo "❌ Error: Could not retrieve API URL from CloudFormation stack"
  exit 1
fi

if [ -z "$WEBSOCKET_URL" ]; then
  echo "❌ Error: Could not retrieve WebSocket URL from CloudFormation stack"
  exit 1
fi

echo "✅ Found API URL: $API_URL"
echo "✅ Found WebSocket URL: $WEBSOCKET_URL"
echo ""

cd ..

# Update frontend config
echo "📝 Updating frontend config..."
cat > frontend/config.js << EOF
// Configuration for the frontend application
// Auto-generated by sync-configs.sh

export const config = {
  aws: {
    region: '${REGION}'
  },
  connect: {
    instanceId: '${INSTANCE_ID}',
    contactFlowId: '${CONTACT_FLOW_ID}'
  },
  api: {
    endpoint: '${API_URL}'
  },
  websocket: {
    url: '${WEBSOCKET_URL}'
  }
};
EOF
echo "✅ Frontend config updated"

# Update agent-app config
echo "📝 Updating agent-app config..."
cat > agent-app/src/config.js << EOF
// Configuration for Amazon Connect Agent Interface
// Auto-generated by sync-configs.sh

export const config = {
    ccpUrl: '${CCP_URL}',
    region: '${REGION}',
    instanceId: '${INSTANCE_ID}'
};
EOF
echo "✅ Agent-app config updated"
echo ""

echo "🔨 Rebuilding frontend with new config..."
cd frontend
npm run build
cd ..
echo "✅ Frontend rebuilt"
echo ""

echo "🔨 Rebuilding agent-app with new config..."
cd agent-app
npm run build
cd ..
echo "✅ Agent-app rebuilt"
echo ""

echo "✅ All configurations synced successfully!"
echo ""
echo "📝 Next step: Redeploy to update S3/CloudFront"
echo "   cd infra && cdk deploy"
