// Configuration for Amazon Connect Agent Interface
// Auto-generated by sync-configs.sh

export const config = {
    ccpUrl: 'https://ajselvar-webcalling.my.connect.aws/ccp-v2/',
    region: 'us-west-2',
    instanceId: '602d4c63-50be-4b56-ac69-6068140d5a61'
};
